## This project is about create a movie recommender based on the Netflix movies. First, we insert a rating database (IMDB maybe) inside the movies list

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

Datasets:

Netflix - https://www.kaggle.com/shivamb/netflix-shows (Kaggle)
IMDB - https://datasets.imdbws.com/

Opening data:

NETFLIX - This dataset consists of tv shows and movies available on Netflix as of 2019. The dataset is collected from Flixable which is a third-party Netflix search engine.

In [2]:
df_netflix = pd.read_csv('./netflix_titles.csv')
df_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

IMDB - Two datasets: one with the ratings, another with the titles.

In [3]:
df_imdb_rat = pd.read_csv('./imdb_ratings.tsv', sep='\t')
df_imdb_rat.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      1623
1  tt0000002            6.1       196
2  tt0000003            6.5      1312
3  tt0000004            6.2       119
4  tt0000005            6.1      2092

In [4]:
df_imdb_titles = pd.read_csv('./imdb_titles.tsv', sep='\t')
df_imdb_titles.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,\N,imdbDisplay,\N,0
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
3,tt0000001,4,Καρμενσίτα,GR,\N,imdbDisplay,\N,0
4,tt0000001,5,Карменсита,RU,\N,imdbDisplay,\N,0

In [5]:
df = df_imdb_titles.copy()

In [6]:
df.dtypes

titleId            object
ordering            int64
title              object
region             object
language           object
types              object
attributes         object
isOriginalTitle    object
dtype: object

In [7]:
df.shape

(22234364, 8)

In [8]:
# We need only the US titles

selecao = df['region'] == 'US'

In [9]:
n1 = df[selecao].shape[0]
n1

1050621

In [10]:
#creating a new dataframe with region = US

df_us = df[selecao]

In [11]:
df_us.head(50)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
5,tt0000001,6,Carmencita,US,\N,\N,\N,0
14,tt0000002,7,The Clown and His Dogs,US,\N,\N,literal English title,0
35,tt0000005,1,Blacksmithing Scene,US,\N,alternative,\N,0
39,tt0000005,5,Blacksmith Scene #1,US,\N,alternative,\N,0
40,tt0000005,6,Blacksmithing,US,\N,\N,informal alternative title,0
43,tt0000005,9,Blacksmith Scene,US,\N,\N,\N,0
46,tt0000006,3,Chinese Opium Den,US,\N,\N,\N,0
50,tt0000007,1,Corbett and Courtney Before the Kinetograph,US,\N,\N,\N,0
54,tt0000007,5,The Corbett-Courtney Fight,US,\N,alternative,\N,0
55,tt0000007,6,Jim Corbett vs. Peter Courtney,US,\N,alternative,\N,0
62,tt0000008,3,"Edison Kinetoscopic Record of a Sneeze, Januar...",US,\N,\N,complete title,0
63,tt0000008,4,Edison Kinetoscopic Record of a Sneeze,US,\N,\N,\N,0
72,tt0000009,4,Miss Jerry,US,\N,\N,\N,0
75,tt0000010,12,Leaving the Factory,US,\N,imdbDisplay,\N,0
80,tt0000010,17,Workers Leaving the Lumière Factory,US,\N,imdbDisplay,\N,0
89,tt0000010,3,Exiting the Factory,US,\N,imdbDisplay,\N,0
91,tt0000010,5,Employees Leaving the Lumière Factory,US,\N,alternative,\N,0
109,tt0000012,1,The Arrival of a Train,US,\N,imdbDisplay,\N,0
120,tt0000012,3,The Arrival of the Mail Train,US,\N,alternative,\N,0
134,tt0000013,4,The Photographical Congress Arrives in Lyon,US,\N,\N,\N,0
150,tt0000014,1,The Sprinkler Sprinkled,US,\N,imdbDisplay,\N,0
151,tt0000014,20,The Waterer Watered,US,\N,imdbDisplay,\N,0
157,tt0000014,2,Tables Turned on the Gardener,US,\N,alternative,\N,0
164,tt0000014,9,The Sprayer Sprayed,US,\N,alternative,\N,0
167,tt0000015,3,Around a Bathing Hut,US,\N,\N,literal English title,0
194,tt0000022,1,The Blacksmiths,US,\N,\N,literal English title,0
199,tt0000022,6,Blacksmith Scene,US,\N,\N,\N,0
209,tt0000023,4,The Sea,US,\N,\N,\N,0
230,tt0000026,5,The Messers. Lumière at Cards,US,\N,\N,\N,0
236,tt0000027,2,Cordeliers' Square in Lyon,US,\N,\N,\N,0
247,tt0000028,7,Fishing for Goldfish,US,\N,\N,\N,0
256,tt0000029,18,Baby's Lunch,US,\N,\N,original script title,0
257,tt0000029,1,Baby's Dinner,US,\N,\N,\N,0
258,tt0000029,2,Feeding the Baby,US,\N,\N,\N,0
278,tt0000031,6,Jumping the Blanket,US,\N,\N,\N,0
291,tt0000033,5,Trick Riding,US,\N,\N,\N,0
300,tt0000035,4,Watering the Flowers,US,\N,\N,\N,0
301,tt0000036,1,Awakening of Rip,US,\N,\N,\N,0
304,tt0000037,1,Sea Bathing,US,\N,imdbDisplay,\N,0
308,tt0000038,1,The Ball Game,US,\N,\N,\N,0
310,tt0000040,1,Boat Leaving the Harbor at Trouville,US,\N,\N,literal English title,0
315,tt0000041,1,Snowball Fight,US,\N,\N,informal English title,0
331,tt0000045,3,The Washerwomen,US,\N,\N,literal English title,0
340,tt0000050,2,Baby and Young Girls,US,\N,\N,literal English title,0
342,tt0000051,1,The Bohemian Encampment,US,\N,\N,\N,0
343,tt0000051,2,Gypsies at Home,US,\N,\N,literal English title,0
353,tt0000054,1,A Merry-Go-Round,US,\N,\N,\N,0
364,tt0000059,1,Coronation of a Village Maiden,US,\N,\N,\N,0
367,tt0000060,1,Dancing Darkies,US,\N,\N,\N,0
377,tt0000067,2,Conjurer Making Ten Hats in Sixty Seconds,US,\N,\N,\N,0

In [12]:
# There are duplicate titles, but the 'ordering' is important. Go to ordenate this column and after keep the 
# first selection of the duplicates
df_us = df_us.sort_values(['titleId', 'ordering'], ascending=[True, True])
df_us.head(50)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
5,tt0000001,6,Carmencita,US,\N,\N,\N,0
14,tt0000002,7,The Clown and His Dogs,US,\N,\N,literal English title,0
35,tt0000005,1,Blacksmithing Scene,US,\N,alternative,\N,0
39,tt0000005,5,Blacksmith Scene #1,US,\N,alternative,\N,0
40,tt0000005,6,Blacksmithing,US,\N,\N,informal alternative title,0
43,tt0000005,9,Blacksmith Scene,US,\N,\N,\N,0
46,tt0000006,3,Chinese Opium Den,US,\N,\N,\N,0
50,tt0000007,1,Corbett and Courtney Before the Kinetograph,US,\N,\N,\N,0
54,tt0000007,5,The Corbett-Courtney Fight,US,\N,alternative,\N,0
55,tt0000007,6,Jim Corbett vs. Peter Courtney,US,\N,alternative,\N,0
62,tt0000008,3,"Edison Kinetoscopic Record of a Sneeze, Januar...",US,\N,\N,complete title,0
63,tt0000008,4,Edison Kinetoscopic Record of a Sneeze,US,\N,\N,\N,0
72,tt0000009,4,Miss Jerry,US,\N,\N,\N,0
89,tt0000010,3,Exiting the Factory,US,\N,imdbDisplay,\N,0
91,tt0000010,5,Employees Leaving the Lumière Factory,US,\N,alternative,\N,0
75,tt0000010,12,Leaving the Factory,US,\N,imdbDisplay,\N,0
80,tt0000010,17,Workers Leaving the Lumière Factory,US,\N,imdbDisplay,\N,0
109,tt0000012,1,The Arrival of a Train,US,\N,imdbDisplay,\N,0
120,tt0000012,3,The Arrival of the Mail Train,US,\N,alternative,\N,0
134,tt0000013,4,The Photographical Congress Arrives in Lyon,US,\N,\N,\N,0
150,tt0000014,1,The Sprinkler Sprinkled,US,\N,imdbDisplay,\N,0
157,tt0000014,2,Tables Turned on the Gardener,US,\N,alternative,\N,0
164,tt0000014,9,The Sprayer Sprayed,US,\N,alternative,\N,0
151,tt0000014,20,The Waterer Watered,US,\N,imdbDisplay,\N,0
167,tt0000015,3,Around a Bathing Hut,US,\N,\N,literal English title,0
194,tt0000022,1,The Blacksmiths,US,\N,\N,literal English title,0
199,tt0000022,6,Blacksmith Scene,US,\N,\N,\N,0
209,tt0000023,4,The Sea,US,\N,\N,\N,0
230,tt0000026,5,The Messers. Lumière at Cards,US,\N,\N,\N,0
236,tt0000027,2,Cordeliers' Square in Lyon,US,\N,\N,\N,0
247,tt0000028,7,Fishing for Goldfish,US,\N,\N,\N,0
257,tt0000029,1,Baby's Dinner,US,\N,\N,\N,0
258,tt0000029,2,Feeding the Baby,US,\N,\N,\N,0
256,tt0000029,18,Baby's Lunch,US,\N,\N,original script title,0
278,tt0000031,6,Jumping the Blanket,US,\N,\N,\N,0
291,tt0000033,5,Trick Riding,US,\N,\N,\N,0
300,tt0000035,4,Watering the Flowers,US,\N,\N,\N,0
301,tt0000036,1,Awakening of Rip,US,\N,\N,\N,0
304,tt0000037,1,Sea Bathing,US,\N,imdbDisplay,\N,0
308,tt0000038,1,The Ball Game,US,\N,\N,\N,0
310,tt0000040,1,Boat Leaving the Harbor at Trouville,US,\N,\N,literal English title,0
315,tt0000041,1,Snowball Fight,US,\N,\N,informal English title,0
331,tt0000045,3,The Washerwomen,US,\N,\N,literal English title,0
340,tt0000050,2,Baby and Young Girls,US,\N,\N,literal English title,0
342,tt0000051,1,The Bohemian Encampment,US,\N,\N,\N,0
343,tt0000051,2,Gypsies at Home,US,\N,\N,literal English title,0
353,tt0000054,1,A Merry-Go-Round,US,\N,\N,\N,0
364,tt0000059,1,Coronation of a Village Maiden,US,\N,\N,\N,0
367,tt0000060,1,Dancing Darkies,US,\N,\N,\N,0
377,tt0000067,2,Conjurer Making Ten Hats in Sixty Seconds,US,\N,\N,\N,0

In [13]:
# Keeping the first titles when are duplicates and removing the others.
df_us = df_us.drop_duplicates(subset='titleId', keep='first')
df_us.head(50)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
5,tt0000001,6,Carmencita,US,\N,\N,\N,0
14,tt0000002,7,The Clown and His Dogs,US,\N,\N,literal English title,0
35,tt0000005,1,Blacksmithing Scene,US,\N,alternative,\N,0
46,tt0000006,3,Chinese Opium Den,US,\N,\N,\N,0
50,tt0000007,1,Corbett and Courtney Before the Kinetograph,US,\N,\N,\N,0
62,tt0000008,3,"Edison Kinetoscopic Record of a Sneeze, Januar...",US,\N,\N,complete title,0
72,tt0000009,4,Miss Jerry,US,\N,\N,\N,0
89,tt0000010,3,Exiting the Factory,US,\N,imdbDisplay,\N,0
109,tt0000012,1,The Arrival of a Train,US,\N,imdbDisplay,\N,0
134,tt0000013,4,The Photographical Congress Arrives in Lyon,US,\N,\N,\N,0
150,tt0000014,1,The Sprinkler Sprinkled,US,\N,imdbDisplay,\N,0
167,tt0000015,3,Around a Bathing Hut,US,\N,\N,literal English title,0
194,tt0000022,1,The Blacksmiths,US,\N,\N,literal English title,0
209,tt0000023,4,The Sea,US,\N,\N,\N,0
230,tt0000026,5,The Messers. Lumière at Cards,US,\N,\N,\N,0
236,tt0000027,2,Cordeliers' Square in Lyon,US,\N,\N,\N,0
247,tt0000028,7,Fishing for Goldfish,US,\N,\N,\N,0
257,tt0000029,1,Baby's Dinner,US,\N,\N,\N,0
278,tt0000031,6,Jumping the Blanket,US,\N,\N,\N,0
291,tt0000033,5,Trick Riding,US,\N,\N,\N,0
300,tt0000035,4,Watering the Flowers,US,\N,\N,\N,0
301,tt0000036,1,Awakening of Rip,US,\N,\N,\N,0
304,tt0000037,1,Sea Bathing,US,\N,imdbDisplay,\N,0
308,tt0000038,1,The Ball Game,US,\N,\N,\N,0
310,tt0000040,1,Boat Leaving the Harbor at Trouville,US,\N,\N,literal English title,0
315,tt0000041,1,Snowball Fight,US,\N,\N,informal English title,0
331,tt0000045,3,The Washerwomen,US,\N,\N,literal English title,0
340,tt0000050,2,Baby and Young Girls,US,\N,\N,literal English title,0
342,tt0000051,1,The Bohemian Encampment,US,\N,\N,\N,0
353,tt0000054,1,A Merry-Go-Round,US,\N,\N,\N,0
364,tt0000059,1,Coronation of a Village Maiden,US,\N,\N,\N,0
367,tt0000060,1,Dancing Darkies,US,\N,\N,\N,0
377,tt0000067,2,Conjurer Making Ten Hats in Sixty Seconds,US,\N,\N,\N,0
379,tt0000068,1,Unloading the Boat,US,\N,\N,\N,0
383,tt0000069,1,Post No Bills,US,\N,\N,\N,0
395,tt0000070,3,Demolition of a Wall,US,\N,\N,literal English title,0
402,tt0000071,1,Automobiles Starting a Race,US,\N,imdbDisplay,\N,0
405,tt0000072,1,Officers of French Army Leaving Service,US,\N,imdbDisplay,\N,0
418,tt0000075,5,The Conjuring of a Woman at the House of Rober...,US,\N,\N,\N,0
424,tt0000076,2,Rip and the Dwarf,US,\N,\N,copyright title,0
438,tt0000081,3,Towing a Boat on the River,US,\N,imdbDisplay,\N,0
439,tt0000082,1,A Hard Wash,US,\N,\N,\N,0
449,tt0000085,1,Gardener Burning Weeds,US,\N,\N,\N,0
452,tt0000086,1,"Beach and Pier at Trouville, 1st part",US,\N,\N,\N,0
457,tt0000087,3,"Beach and Pier at Trouville, 2nd part",US,\N,\N,\N,0
460,tt0000088,3,Market Day,US,\N,\N,\N,0
484,tt0000091,7,The Haunted Castle,US,\N,dvd,\N,0
495,tt0000095,2,The Mysterious Paper,US,\N,\N,\N,0
498,tt0000097,1,"Place de l'Opéra, First View",US,\N,\N,\N,0
501,tt0000098,1,"Place de l'Opéra, Second View",US,\N,\N,\N,0

In [14]:
df_us.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 989625 entries, 5 to 22234110
Data columns (total 8 columns):
titleId            989625 non-null object
ordering           989625 non-null int64
title              989625 non-null object
region             989625 non-null object
language           989625 non-null object
types              989625 non-null object
attributes         989625 non-null object
isOriginalTitle    989625 non-null object
dtypes: int64(1), object(7)
memory usage: 68.0+ MB

In [28]:
#Verifying the situation, if there are only unique values in titleId
df_us['titleId'].is_unique

True